spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/da?serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
    username: root
    password:
  jpa:
   hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


##\u5206\u9875pageHelper
#pagehelper.helperDialect=mysql
#pagehelper.reasonable=true
#pagehelper.supportMethodsArguments=true
#pagehelper.params=count=countSql
#pagehelper.page-size-zero=true